Repository bifrost-platform/bifrost-relayer.rs, pull requests merged in 2023-08, with the labels that each got.

#83 CCCP-212, fix: txpool namespace verification
  client/src/eth/tx/eip1559_manager.rs
  client/src/eth/tx/legacy_manager.rs
Labels: bug

#82 CCCP-210, feature: support dai price oracle on testnet
  configs/config.testnet.yaml
  periodic/src/price_source/chainlink.rs
  periodic/src/price_source/coingecko.rs
  primitives/src/cli.rs
  primitives/src/eth.rs
  relayer/src/service.rs
Labels: enhancement

#86 Remove SonarQube files
  .github/workflows/sonar.yaml
Labels: chore

#87 CCCP-199, feature: introduce Base network
  client/src/eth/handlers/bridge_relay_handler.rs
  client/src/eth/tx/eip1559_manager.rs
  client/src/eth/tx/legacy_manager.rs
  configs/config.mainnet.yaml
  configs/config.testnet.yaml
  periodic/src/price_source/chainlink.rs
  periodic/src/price_source/coingecko.rs
  primitives/src/cli.rs
  primitives/src/contracts/socket.rs
  primitives/src/eth.rs
  relayer/Cargo.toml
  relayer/src/service.rs
Labels: enhancement
