Repository bifrost-platform/bifrost-relayer.rs, pull requests merged in 2023-09, with the labels that each got.

#88 [CCCP-224] error on switching legacy <-> eip1559 tx_handler
  client/src/eth/tx/eip1559_manager.rs
  client/src/eth/tx/legacy_manager.rs
  primitives/src/cli.rs
  primitives/src/errors.rs
  relayer/src/service.rs
Labels: bug

#89 CCCP-228, feature: enhance bootstrap verifications
  .gitignore
  client/src/eth/blocks.rs
  client/src/eth/mod.rs
  client/src/eth/tx/eip1559_manager.rs
  client/src/eth/tx/legacy_manager.rs
  configs/config.mainnet.yaml
  configs/config.testnet.yaml
  periodic/src/price_feeder.rs
  primitives/src/errors.rs
  sonar-project.properties
Labels: chore, enhancement

#90 CCCP-229, feature: balance check before sending transactions
  client/src/eth/blocks.rs
  client/src/eth/mod.rs
  client/src/eth/tx/eip1559_manager.rs
  client/src/eth/tx/legacy_manager.rs
  client/src/eth/tx/mod.rs
  primitives/src/errors.rs
Labels: enhancement

#91 CCCP-247 feature, provide get logs batch size option
  client/src/eth/blocks.rs
  client/src/eth/handlers/bridge_relay_handler.rs
  client/src/eth/handlers/roundup_relay_handler.rs
  client/src/eth/mod.rs
  client/src/eth/tx/legacy_manager.rs
  periodic/src/roundup_emitter.rs
  primitives/src/cli.rs
  primitives/src/errors.rs
  primitives/src/eth.rs
  relayer/src/service.rs
Labels: enhancement

#92 CCCP-232, deploy: release v1.0.4
  Cargo.toml
  client/src/eth/tx/legacy_manager.rs
  primitives/src/cli.rs
  relayer/Cargo.toml
  relayer/src/service.rs
  rust-toolchain
Labels: release
