Repository bifrost-platform/bifrost-relayer.rs, pull requests merged in 2024-06, with the labels that each got.

#131 CCCP-384, feat: impl rollback poll
  abi/abi.registration_pool.bifrost.json
  abi/abi.socket_queue.bifrost.json
  client/src/btc/handlers/inbound.rs
  client/src/btc/handlers/mod.rs
  configs/bifrost_metadata.scale
  periodic/src/bitcoin_rollback_verifier.rs
  periodic/src/lib.rs
  primitives/src/constants/schedule.rs
  primitives/src/substrate.rs
  primitives/src/tx.rs
  relayer/src/service.rs
Labels: enhancement

#132 [CCCP-385] registration-pool migration process
  abi/abi.registration_pool.bifrost.json
  abi/abi.socket_queue.bifrost.json
  client/src/btc/block.rs
  client/src/btc/handlers/inbound.rs
  client/src/btc/handlers/mod.rs
  client/src/btc/handlers/psbt_signer.rs
  client/src/btc/storage/keypair.rs
  client/src/eth/handlers/roundup_relay_handler.rs
  client/src/eth/handlers/socket_relay_handler.rs
  client/src/eth/mod.rs
  client/src/eth/traits.rs
  client/src/substrate/traits.rs
  client/src/substrate/tx/unsigned_manager.rs
  configs/bifrost_metadata.scale
  periodic/src/bitcoin_rollback_verifier.rs
  periodic/src/keypair_migrator.rs
  periodic/src/lib.rs
  periodic/src/price_feeder.rs
  periodic/src/pub_key_submitter.rs
  periodic/src/socket_rollback_emitter.rs
  primitives/src/constants/schedule.rs
  primitives/src/substrate.rs
  primitives/src/tx.rs
  relayer/src/service.rs
Labels: enhancement

#135 Bootstrap config minor update
  client/src/btc/block.rs
  configs/config.mainnet.yaml
  configs/config.testnet.yaml
  primitives/src/cli.rs
  relayer/src/service.rs
Labels: chore

#136 deps: update subxt version
  Cargo.toml
  primitives/src/tx.rs
Labels: chore, dependencies

#137 [CCCP-403] Implement `PubKeyPreSubmitter`
  client/src/btc/handlers/mod.rs
  configs/bifrost_metadata.scale
  periodic/src/lib.rs
  periodic/src/price_source/coingecko.rs
  periodic/src/pub_key_presubmitter.rs
  periodic/src/pub_key_submitter.rs
  primitives/src/constants/schedule.rs
  primitives/src/substrate.rs
  primitives/src/tx.rs
  relayer/src/service.rs
Labels: enhancement

#138 fix: simply use txid instead of psbt bytes
  configs/bifrost_metadata.scale
  periodic/src/bitcoin_rollback_verifier.rs
  primitives/src/tx.rs
Labels: chore
