Repository bifrost-platform/bifrost-relayer.rs, pull requests merged in 2024-01, with the labels that each got.

#103 CCCP-306, fix: socket variants issue
  client/src/eth/handlers/socket_relay_handler.rs
  configs/config.testnet.yaml
  relayer/src/main.rs
Labels: bug

#105 CCCP-304, Replace GasEscalatorMiddleware with stalled tx handler
  client/src/eth/events.rs
  client/src/eth/tx/eip1559_manager.rs
  client/src/eth/tx/legacy_manager.rs
  client/src/eth/tx/task.rs
  primitives/src/cli.rs
  relayer/src/service.rs
  relayer/src/verification.rs
Labels: bug, chore

#106 CCCP-313, BTC price feed
  configs/config.mainnet.yaml
  configs/config.testnet.yaml
  periodic/src/price_source/chainlink.rs
  periodic/src/price_source/coingecko.rs
  primitives/src/cli.rs
  primitives/src/eth.rs
  relayer/src/service.rs
Labels: chore

#109 CCCP-321, deps: release v1.1.0
  configs/config.mainnet.yaml
  configs/config.testnet.yaml
  relayer/Cargo.toml
  rust-toolchain
Labels: dependencies
