Repository bifrost-platform/bifrost-relayer.rs, pull requests merged in 2024-10, with the labels that each got.

#157 CCCP-453, deps: update mainnet config
  configs/config.mainnet.yaml
Labels: dependencies

#159 fix: use correct `to_block`
  client/src/btc/block.rs
Labels: bug

#160 Mute sentry on BtcSocketQueue::RequestDNE
  .gitignore
  client/src/substrate/traits.rs
Labels: chore
