Repository bifrost-platform/bifrost-relayer.rs, pull requests merged in 2024-04, with the labels that each got.

#115 CCCP-360, feature: add precompile contract instances
  abi/abi.registration_pool.bifrost.json
  abi/abi.relay_executive.bifrost.json
  abi/abi.socket_queue.bifrost.json
  configs/config.mainnet.yaml
  configs/config.testnet.yaml
  primitives/src/cli.rs
  primitives/src/contracts/mod.rs
  primitives/src/contracts/registration_pool.rs
  primitives/src/contracts/relay_executive.rs
  primitives/src/contracts/socket_queue.rs
  primitives/src/eth.rs
  relayer/src/service.rs
Labels: chore

#117 chore: update precompile abi
  abi/abi.registration_pool.bifrost.json
  abi/abi.socket_queue.bifrost.json
Labels: chore

#120 CCCP-370, deps: deprecate mumbai chain
  configs/config.testnet.yaml
Labels: dependencies

#121 CCCP-367, chore: cleanup code
  client/src/btc/block.rs
  client/src/btc/handlers/inbound.rs
  client/src/btc/handlers/mod.rs
  client/src/btc/handlers/outbound.rs
  client/src/btc/mod.rs
  client/src/btc/storage/keypair.rs
  client/src/btc/storage/pending_outbound.rs
  client/src/substrate/traits.rs
  client/src/substrate/tx/unsigned_manager.rs
  configs/config.mainnet.yaml
  configs/config.testnet.yaml
  periodic/src/pub_key_submitter.rs
  primitives/src/cli.rs
  primitives/src/constants/cli.rs
  primitives/src/constants/errors.rs
  primitives/src/eth.rs
  primitives/src/tx.rs
  relayer/src/service.rs
Labels: chore

#118 CCCP-362, feature: implement psbt signer & pub key submitter
  Cargo.toml
  abi/abi.registration_pool.bifrost.json
  client/Cargo.toml
  client/src/btc/block.rs
  client/src/btc/handlers/inbound.rs
  client/src/btc/handlers/mod.rs
  client/src/btc/handlers/outbound.rs
  client/src/btc/handlers/psbt_signer.rs
  client/src/btc/mod.rs
  client/src/btc/storage/keypair.rs
  client/src/btc/storage/pending_outbound.rs
  client/src/eth/events.rs
  client/src/eth/handlers/roundup_relay_handler.rs
  client/src/eth/handlers/socket_relay_handler.rs
  client/src/eth/mod.rs
  client/src/eth/traits.rs
  client/src/eth/tx/eip1559_manager.rs
  client/src/eth/tx/legacy_manager.rs
  client/src/substrate/traits.rs
  client/src/substrate/tx/unsigned_manager.rs
  configs/config.mainnet.yaml
  configs/config.testnet.yaml
  periodic/Cargo.toml
  periodic/src/heartbeat_sender.rs
  periodic/src/lib.rs
  periodic/src/price_feeder.rs
  periodic/src/price_source/coingecko.rs
  periodic/src/pub_key_submitter.rs
  periodic/src/roundup_emitter.rs
  periodic/src/socket_rollback_emitter.rs
  primitives/Cargo.toml
  primitives/src/cli.rs
  primitives/src/constants/cli.rs
  primitives/src/constants/errors.rs
  primitives/src/constants/schedule.rs
  primitives/src/eth.rs
  primitives/src/lib.rs
  primitives/src/substrate.rs
  primitives/src/tx.rs
  primitives/src/utils.rs
  relayer/src/cli.rs
  relayer/src/service.rs
Labels: enhancement

#116 CCCP-359, feature: init substrate modules
  Cargo.toml
  abi/abi.registration_pool.bifrost.json
  client/Cargo.toml
  client/src/btc/block.rs
  client/src/btc/handlers/inbound.rs
  client/src/btc/handlers/mod.rs
  client/src/btc/handlers/outbound.rs
  client/src/btc/handlers/psbt_signer.rs
  client/src/btc/mod.rs
  client/src/btc/storage/keypair.rs
  client/src/btc/storage/pending_outbound.rs
  client/src/eth/events.rs
  client/src/eth/handlers/roundup_relay_handler.rs
  client/src/eth/handlers/socket_relay_handler.rs
  client/src/eth/mod.rs
  client/src/eth/traits.rs
  client/src/eth/tx/eip1559_manager.rs
  client/src/eth/tx/legacy_manager.rs
  client/src/lib.rs
  client/src/substrate/mod.rs
  client/src/substrate/traits.rs
  client/src/substrate/tx/mod.rs
  client/src/substrate/tx/unsigned_manager.rs
  configs/bifrost_metadata.scale
  configs/config.mainnet.yaml
  configs/config.testnet.yaml
  periodic/Cargo.toml
  periodic/src/heartbeat_sender.rs
  periodic/src/lib.rs
  periodic/src/price_feeder.rs
  periodic/src/price_source/coingecko.rs
  periodic/src/pub_key_submitter.rs
  periodic/src/roundup_emitter.rs
  periodic/src/socket_rollback_emitter.rs
  periodic/src/traits.rs
  primitives/Cargo.toml
  primitives/src/bootstrap.rs
  primitives/src/cli.rs
  primitives/src/constants/cli.rs
  primitives/src/constants/errors.rs
  primitives/src/constants/schedule.rs
  primitives/src/eth.rs
  primitives/src/lib.rs
  primitives/src/substrate.rs
  primitives/src/tx.rs
  primitives/src/utils.rs
  relayer/Cargo.toml
  relayer/src/cli.rs
  relayer/src/service.rs
Labels: enhancement

#125 CCCP-382: feature: Arbitrum `eth_syncing` response format
  Cargo.toml
  client/src/eth/events.rs
Labels: bug, enhancement

#123 CCCP-371, feature: bitcoin inbound & outbound bootstrap
  client/src/btc/block.rs
  client/src/btc/handlers/inbound.rs
  client/src/btc/handlers/mod.rs
  client/src/btc/handlers/outbound.rs
  client/src/btc/storage/keypair.rs
  client/src/eth/events.rs
  client/src/eth/handlers/roundup_relay_handler.rs
  client/src/eth/handlers/socket_relay_handler.rs
  client/src/eth/mod.rs
  client/src/eth/traits.rs
  periodic/src/heartbeat_sender.rs
  periodic/src/pub_key_submitter.rs
  periodic/src/roundup_emitter.rs
  primitives/src/bootstrap.rs
  primitives/src/constants/config.rs
  relayer/src/service.rs
Labels: enhancement

#126 alex/allow zero bootstrap
  client/src/btc/block.rs
Labels: bug

#127 Alex/minor fixes (2)
  client/src/btc/block.rs
  client/src/btc/handlers/inbound.rs
  client/src/btc/handlers/outbound.rs
  client/src/eth/handlers/socket_relay_handler.rs
  client/src/eth/mod.rs
  periodic/src/socket_rollback_emitter.rs
  primitives/src/eth.rs
  relayer/src/service.rs
Labels: chore
